export const dummmyHiresData = [
    {
        id: crypto.randomUUID(),
        display: '0',
        slug: 'Frontend-Developer',
        application: 'https://analogueshifts.com',
        role: 'Frontend Developer',
        hire_type: 'Remote',
        range: '$18K',
        experience: '5 years',
        duration: '10 Months',
        description: '<p>This is a Technical Role</p>',
        status: 'Approved',
    },
    {
        id: crypto.randomUUID(),
        display: '0',
        slug: 'Backend-Developer',
        application: 'https://analogueshifts.com',
        role: 'Backend Developer',
        hire_type: 'Remote',
        range: '$18K',
        experience: '5 years',
        duration: '10 Months',
        description: '<p>This is a Technical Role</p>',
        status: 'Approved',
    },
]
